FROM node:22-alpine AS builder

WORKDIR /home/app

COPY package*.json ./
RUN npm ci

COPY . .

RUN npm run build && npm prune --omit=dev

FROM node:22-alpine AS runner

WORKDIR /home/app

RUN addgroup -S appgroup && adduser -S appuser -G appgroup

COPY --from=builder /home/app/node_modules ./node_modules
COPY --from=builder /home/app/dist ./dist
COPY --from=builder /home/app/package.json ./

RUN chown -R appuser:appgroup /home/app

USER appuser

EXPOSE 5050

CMD ["node", "dist/server.js"]
